### ISSUE TITLE
Aplodontidae and Dipodidae higher taxonomy.

### ISSUE THREAD

**Issue by karilint** [nowcommunity/NOW-Data#33]

**Comment by karilint** [comment]
After entering Gudrun’s Mongolia data we noted inconsistencies in higher level taxonomomy for Aplodontidae and Dipodidae. Someone should review this and check for inconsistencies. Maybe we could extract the species list and send it to someone for review. Good candidates to do this are Larry Flynn and for Dipodidae either Yuri Kimura or Maxim Sinitsa (which are not part of the NOW but surely will be glad to help).

**Comment by zliobaite** [comment]
Isaac
